// Assignment Code

// Character choices array
let charArr = ["ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz", "0123456789", "!#$%?"];

/* 

*** TODO make randPassArr always generate a password with all desired chars *** 

*/

// Add click event
let displayPass = document.getElementById('generate');
displayPass.addEventListener('click', generatePassword);

// Generate random password function

function generatePassword() {
  let randPassArr = [];
  let password = [];
  let passCharStr = [];
  // ask user to pick password length
  let userLenChars = prompt("Choose a password length between 8 & 128 characters");

  // function alerts user that their password would be safer if they included the extra chars
  let safePrompt = function() {
    alert('It\'d be safer if you did!')
  };

  // ask the user if they would like to include uppecase, lowercase, numerical and/or special characters.
  // use user input from promts to generate password array
  if (userLenChars === null || userLenChars == '' || userLenChars < 8 || userLenChars > 128) {
    return userLenChars;
  } else {
    let userUpChars = confirm("Would you like UPPERCASE characters?");
    userUpChars ? password.push(charArr[0]) : safePrompt();
    
    let userLowChars = confirm("Would you like lowercase characters?");
    userLowChars ? password.push(charArr[1]) : safePrompt();
    
    let userNumChars = confirm("Would you like num3r1ca1 characters?");
    userNumChars ? password.push(charArr[2]) : safePrompt();

    let userSpecChars = confirm("Would you like $pec!al characters?");
    userSpecChars ? password.push(charArr[3]) : safePrompt();
    }
  for (arr of password) {
    passCharStr += arr;
  }
  do {
    randPassArr.push(passCharStr[Math.floor(Math.random() * passCharStr.length)])
    
  } while (randPassArr.length < userLenChars)
   console.log(randPassArr.join(''))
  return document.getElementById('password').innerHTML = randPassArr.join(""); 

}

/*   
    ***Increase performance***
  
However, it doesn’t work quite as well as I think it could. The function generates a random password 
but it doesn’t always include all of the characters the user requests.
The user could request all 4 characters but sometimes the function will only return 3 or less different char types in the generated password). 

Try to write an if statement (on line 78) of sorts to check if the string generated by randPassArr 
includes all of the requested characters. Maybe a regular expression?

*/

  /* revert back to this if above doesn't work out */

/*     if (userUpChars) {
      password.push(charArr[0]);
      randPassArr.push(charArr[0][Math.floor(Math.random() * charArr[0].length)]);

    } else {
      alert('It\'d be safer if you did!')
    }
    let userLowChars = confirm("Would you like lowercase characters?");

    if (userLowChars) {
      password.push(charArr[1]);
      randPassArr.push(charArr[1][Math.floor(Math.random() * charArr[1].length)]);

    } else {
      alert('It\'d be safer if you did!')
    }
    let userNumChars = confirm("Would you like num3r1ca1 characters?");

    if (userNumChars) {
      password.push(charArr[2]);
      randPassArr.push(charArr[2][Math.floor(Math.random() * charArr[2].length)]);

    } else {
      alert('It\'d be safer if you did!')
    }
    let userSpecChars = confirm("Would you like $pec!al characters?");

    if (userSpecChars) {
      password.push(charArr[3]);
      randPassArr.push(charArr[3][Math.floor(Math.random() * charArr[3].length)]);

    } else {
      alert('It\'d be safer if you did!')
    } 

    // join password arrays into one array
     passCharStr = password.join(""); 
     
  }
 */
  // try for a better solution
  // different type of loop passCharStr.forEach(x => { x[Math.floor(Math.random() * passCharStr.length)]}) 
  // or something of the sort.
  /* for (let i = 0; i < userLenChars; i++) {
    if (randPassArr.length < userLenChars) {
      randPassArr.push(passCharStr[Math.floor(Math.random() * passCharStr.length)]);
    }
  }

  console.log(randPassArr);
  return document.getElementById('password').innerHTML = randPassArr.join(""); 
};
*/
